import{a as n,i as h,S as m}from"./assets/vendor-f2ddc932.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const y="live_WBAXg2spdkwyhrllREaQ2aUDs97gq6IhSDZKEvd663sDi13vUZD45ddW3MHz3u6C",p="https://api.thecatapi.com/v1",g="breeds",v="images/search";n.defaults.headers.common["x-api-key"]=y;const S=async()=>{const t=await n.get(`${p}/${g}`);if(!t||t.status!==200)throw new Error(t.statusText);return t.data},L=async t=>{const r=new URLSearchParams({breed_ids:t}),o=await n.get(`${p}/${v}?${r}`);if(!o||o.status!==200)throw new Error(o.statusText);return o.data},c=document.querySelector(".breed-select"),d=document.querySelector(".loader-text"),u=document.querySelector(".loader"),l=document.querySelector(".error"),w=document.querySelector(".cat-info");l.classList.add("visually-hidden");c.classList.add("visually-hidden");S().then(t=>{E(t),c.classList.remove("visually-hidden"),d.classList.add("visually-hidden"),u.classList.add("visually-hidden")}).catch(()=>{d.classList.add("visually-hidden"),u.classList.add("visually-hidden"),l.classList.remove("visually-hidden"),h.show({title:"date",color:"red",position:"topCenter",message:"Oops! Something went wrong! Try reloading the page!"})});function E(t){new m({select:"#selectElement",data:[...t.map(r=>({text:r.name,value:r.id}))],option:{},settings:{searchPlaceholder:"Search",hideSelected:!0,display:!1,hideSelected:!0}})}c.addEventListener("change",t=>{t.preventDefault();const{value:r}=t.target;L(r).then(o=>R(o)).catch(()=>{l.classList.remove("visually-hidden"),h.show({title:"date",color:"red",position:"topCenter",message:"Oops! Something went wrong! Try reloading the page!"})})});const R=t=>{const{url:r,breeds:o}=t[0],{name:i,alt_names:e,description:s,temperament:a}=o[0],f=`
  <div class='imgWripper'>
    <img src=${r} width=100% height=500 alt=${e}/>  
  </div>
  <div class='descriptionWripper'>
    <h2 class='title'>${i}</h2>
    <p class='description'>${s}</p>
    <h3 class='subtitle'>${a}</h3>
  </div>
  `;w.innerHTML=f};
//# sourceMappingURL=commonHelpers.js.map
