import{a as i,i as l,S as p}from"./assets/vendor-50bfee9d.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const f="live_WBAXg2spdkwyhrllREaQ2aUDs97gq6IhSDZKEvd663sDi13vUZD45ddW3MHz3u6C",d="https://api.thecatapi.com/v1",m="breeds",g="images/search";i.defaults.headers.common["x-api-key"]=f;const y=async()=>{const t=await i.get(`${d}/${m}`);if(!t||t.status!==200)throw new Error(t.statusText);return t.data},S=async t=>{const r=new URLSearchParams({breed_ids:t}),o=await i.get(`${d}/${g}?${r}`);if(!o||o.status!==200)throw new Error(o.statusText);return o.data},u=document.querySelector(".breed-select"),v=document.querySelector(".loader-text"),c=document.querySelector(".loader"),w=document.querySelector(".error"),L=document.querySelector(".cat-info");w.classList.add("visually-hidden");u.classList.add("visually-hidden");v.classList.add("visually-hidden");y().then(t=>{E(t),u.classList.remove("visually-hidden"),c.classList.add("visually-hidden")}).catch(()=>{c.classList.add("visually-hidden"),l.show({title:"date",color:"red",position:"topCenter",message:"Oops! Something went wrong! Try reloading the page!"})});function E(t){new p({select:"#selectElement",data:[...t.map(r=>({text:r.name,value:r.id}))],option:{},settings:{searchPlaceholder:"Search",hideSelected:!0,display:!1,hideSelected:!0,placeholderText:"Select Value"},events:{afterChange:R}})}const R=t=>{const r=t.map(o=>o.value).toString();S(r).then(o=>T(o)).catch(()=>{l.show({title:"date",color:"red",position:"topCenter",message:"Oops! Something went wrong! Try reloading the page!"})})},T=t=>{const{url:r,breeds:o}=t[0],{name:n,alt_names:e,description:s,temperament:a}=o[0],h=`
  <div class='imgWripper'>
    <img src=${r} width=100% height=500 alt=${e}/>  
  </div>
  <div class='descriptionWripper'>
    <h2 class='title'>${n}</h2>
    <p class='description'>${s}</p>
    <h3 class='subtitle'>${a}</h3>
  </div>
  `;L.innerHTML=h};
//# sourceMappingURL=commonHelpers.js.map
